#!/bin/bash
script=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

while getopts ":f" opt; do
    case $opt in
        f) full="yes";;
        \?) echo "Usage: check [-f]" 1>&2 && exit 1;;
    esac
done
[ ! -z $full ] && $script/install

cp $script/Vimwolf.m $script/test/Vimwolf.m

for f in $script/test/*.m; do
   vim +"syn on" +"set nonu" +"run! syntax/2html.vim" +"wq" +"q" $f
   sed -i -e '0,/<pre/d' -e '/<\/pre/,$d' $f.html
   diff -U 0 $f.test $f.html > $f.diff
done

err=0
for f in $script/test/*.diff; do
   echo -n "Checking $f ... "
   [ -z "$(cat $f)" ] && echo -e "\e[32mok\e[39m" || { echo -e "\e[31merror\e[39m"; ((err++)); }
done
   [ $err -eq 0 ] || exit 1
